### ISSUE TITLE
Tracker not tracking anything

### ISSUE THREAD

**Issue by DrDiabetus** [KrisDavie/DoorTracker#1]
I start SNI, start the game and connect it to SNI using lua. Afterwards Iaunch DoorTracker, which seems to connect correctly to SNI. It works manually but doesn't autotrack anything.

![image](https://user-images.githubusercontent.com/54161571/231867708-33d5b9fa-bc31-4375-a502-4b7c6226c933.png)
![image](https://user-images.githubusercontent.com/54161571/231867967-da13bc6c-1bdb-49dc-b358-0ac6e1870cb6.png)

I already have all required Python librarys installed, but can't seem to figure out what I'm missing. Wondering if this error is on my side doing something wrong or due to its still early developement

**Comment by KrisDavie** [comment]
Hey @DrDiabetus 

Thanks for the report. I've exclusively tested this using an FXPAK Pro on a SuperNT up until now, it's possible that the memory addresses are different when connecting via luabridge (I think I saw something about that in the SNI docs) so I'd have to test with that. It'll be a little lower on my priority list for now, but I'll update here if I get it working via emulator.

**Comment by KrisDavie** [comment]
Turns out this was a trivial fix and it should work in the latest update.

Fixed in 220697c
